// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBBsB4HaiXJz24c0wnipI6_d1_SOiWoQgI',
//     appId: '1:484573516548:web:88aa66ca1902bd6a73f651',
//     messagingSenderId: '484573516548',
//     projectId: 'weatherapp-e3281',
//     authDomain: 'weatherapp-e3281.firebaseapp.com',
//     storageBucket: 'weatherapp-e3281.appspot.com',
//     measurementId: 'G-9RYHKKGLRB',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDsAGuhbq4ui8Wqsdsf3pIkAQXoZqhCvns',
//     appId: '1:484573516548:android:1e478e2ec5a5bfa973f651',
//     messagingSenderId: '484573516548',
//     projectId: 'weatherapp-e3281',
//     storageBucket: 'weatherapp-e3281.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCUW3tQKTyK4jvT196ucQTgwRJkoGo-0lw',
//     appId: '1:484573516548:ios:91e63b85c94b0c5473f651',
//     messagingSenderId: '484573516548',
//     projectId: 'weatherapp-e3281',
//     storageBucket: 'weatherapp-e3281.appspot.com',
//     iosClientId: '484573516548-p3j1ii2ueclkc6hcjpj9h2m421qb3qr8.apps.googleusercontent.com',
//     iosBundleId: 'com.example.weatherApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCUW3tQKTyK4jvT196ucQTgwRJkoGo-0lw',
//     appId: '1:484573516548:ios:de710c40fa47ebf973f651',
//     messagingSenderId: '484573516548',
//     projectId: 'weatherapp-e3281',
//     storageBucket: 'weatherapp-e3281.appspot.com',
//     iosClientId: '484573516548-6f5sgfk77ucfqj2hinfltkljduoa7d9a.apps.googleusercontent.com',
//     iosBundleId: 'com.example.weatherApp.RunnerTests',
//   );
// }
